import React, {useRef} from 'react';
import Layout from '../components/Layout';
import gsap from "gsap";
import { ScrollTrigger } from 'gsap/ScrollTrigger';

const Shows = () => {


    return (
        <>
        <div style={{height: '100vh'}}>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl vel pretium lectus quam id leo. Non curabitur gravida arcu ac. Pellentesque elit eget gravida cum sociis natoque. Volutpat blandit aliquam etiam erat velit scelerisque. Bibendum est ultricies integer quis auctor elit sed. Orci dapibus ultrices in iaculis nunc sed augue lacus. Vitae proin sagittis nisl rhoncus mattis rhoncus urna. Sed faucibus turpis in eu mi. Eget mi proin sed libero enim sed faucibus turpis. Ultricies integer quis auctor elit. Tempor orci eu lobortis elementum nibh tellus molestie nunc. Ac tincidunt vitae semper quis lectus nulla at volutpat. A cras semper auctor neque. Pharetra et ultrices neque ornare aenean euismod elementum nisi quis. Sit amet est placerat in egestas erat imperdiet. Tincidunt arcu non sodales neque sodales. Non diam phasellus vestibulum lorem sed risus.
        Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Mattis pellentesque id nibh tortor id. Elementum eu facilisis sed odio. Orci eu lobortis elementum nibh. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Et odio pellentesque diam volutpat commodo sed. Diam vulputate ut pharetra sit amet aliquam. Nunc consequat interdum varius sit amet mattis. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Sit amet nisl suscipit adipiscing bibendum est ultricies integer quis. Mattis pellentesque id nibh tortor id aliquet. Orci sagittis eu volutpat odio. Viverra nam libero justo laoreet sit amet.
        Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Mattis pellentesque id nibh tortor id. Elementum eu facilisis sed odio. Orci eu lobortis elementum nibh. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Et odio pellentesque diam volutpat commodo sed. Diam vulputate ut pharetra sit amet aliquam. Nunc consequat interdum varius sit amet mattis. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Sit amet nisl suscipit adipiscing bibendum est ultricies integer quis. Mattis pellentesque id nibh tortor id aliquet. Orci sagittis eu volutpat odio. Viverra nam libero justo laoreet sit amet.
        </p>
        </div>
        <div style={{height: '100vh', backgroundColor: 'tan'}}>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl vel pretium lectus quam id leo. Non curabitur gravida arcu ac. Pellentesque elit eget gravida cum sociis natoque. Volutpat blandit aliquam etiam erat velit scelerisque. Bibendum est ultricies integer quis auctor elit sed. Orci dapibus ultrices in iaculis nunc sed augue lacus. Vitae proin sagittis nisl rhoncus mattis rhoncus urna. Sed faucibus turpis in eu mi. Eget mi proin sed libero enim sed faucibus turpis. Ultricies integer quis auctor elit. Tempor orci eu lobortis elementum nibh tellus molestie nunc. Ac tincidunt vitae semper quis lectus nulla at volutpat. A cras semper auctor neque. Pharetra et ultrices neque ornare aenean euismod elementum nisi quis. Sit amet est placerat in egestas erat imperdiet. Tincidunt arcu non sodales neque sodales. Non diam phasellus vestibulum lorem sed risus.
        Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Mattis pellentesque id nibh tortor id. Elementum eu facilisis sed odio. Orci eu lobortis elementum nibh. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Et odio pellentesque diam volutpat commodo sed. Diam vulputate ut pharetra sit amet aliquam. Nunc consequat interdum varius sit amet mattis. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Sit amet nisl suscipit adipiscing bibendum est ultricies integer quis. Mattis pellentesque id nibh tortor id aliquet. Orci sagittis eu volutpat odio. Viverra nam libero justo laoreet sit amet.
        Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Mattis pellentesque id nibh tortor id. Elementum eu facilisis sed odio. Orci eu lobortis elementum nibh. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Et odio pellentesque diam volutpat commodo sed. Diam vulputate ut pharetra sit amet aliquam. Nunc consequat interdum varius sit amet mattis. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Sit amet nisl suscipit adipiscing bibendum est ultricies integer quis. Mattis pellentesque id nibh tortor id aliquet. Orci sagittis eu volutpat odio. Viverra nam libero justo laoreet sit amet.
        </p>
        </div>
     <div style={{height: '100vh'}}>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl vel pretium lectus quam id leo. Non curabitur gravida arcu ac. Pellentesque elit eget gravida cum sociis natoque. Volutpat blandit aliquam etiam erat velit scelerisque. Bibendum est ultricies integer quis auctor elit sed. Orci dapibus ultrices in iaculis nunc sed augue lacus. Vitae proin sagittis nisl rhoncus mattis rhoncus urna. Sed faucibus turpis in eu mi. Eget mi proin sed libero enim sed faucibus turpis. Ultricies integer quis auctor elit. Tempor orci eu lobortis elementum nibh tellus molestie nunc. Ac tincidunt vitae semper quis lectus nulla at volutpat. A cras semper auctor neque. Pharetra et ultrices neque ornare aenean euismod elementum nisi quis. Sit amet est placerat in egestas erat imperdiet. Tincidunt arcu non sodales neque sodales. Non diam phasellus vestibulum lorem sed risus.
        Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Mattis pellentesque id nibh tortor id. Elementum eu facilisis sed odio. Orci eu lobortis elementum nibh. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Et odio pellentesque diam volutpat commodo sed. Diam vulputate ut pharetra sit amet aliquam. Nunc consequat interdum varius sit amet mattis. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Sit amet nisl suscipit adipiscing bibendum est ultricies integer quis. Mattis pellentesque id nibh tortor id aliquet. Orci sagittis eu volutpat odio. Viverra nam libero justo laoreet sit amet.
        Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Mattis pellentesque id nibh tortor id. Elementum eu facilisis sed odio. Orci eu lobortis elementum nibh. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Et odio pellentesque diam volutpat commodo sed. Diam vulputate ut pharetra sit amet aliquam. Nunc consequat interdum varius sit amet mattis. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Sit amet nisl suscipit adipiscing bibendum est ultricies integer quis. Mattis pellentesque id nibh tortor id aliquet. Orci sagittis eu volutpat odio. Viverra nam libero justo laoreet sit amet.
        </p>
        </div>
        </>
    )
}
export default Shows;